name: devaldaporto
description: A new Flutter project.

# publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  provider: ^6.0.5
  get: ^4.6.5
  http: ^0.13.5
  quotes_widget: ^0.0.2
  font_awesome_flutter: ^10.3.0
  coachmaker: ^0.2.1
  confetti: ^0.7.0
  animated_text_kit: ^4.2.2
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  rive: ^0.10.1
  url_launcher: ^6.1.9
  animated_gradient: ^0.0.2
  animate_gradient: ^0.0.2
  flutter_markdown: ^0.6.14
  shared_preferences: ^2.0.17
  flutter_spinkit: ^5.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
  flutter_launcher_icons: ^0.11.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/iconlauncher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # Rive asset
    - assets/RiveAssets/Icons.riv
    - assets/RiveAssets/Logo.riv
    - assets/RiveAssets/Rocket.riv
    - assets/RiveAssets/Robot.riv
    - assets/RiveAssets/Bird.riv
    - assets/RiveAssets/Love.riv
    - assets/RiveAssets/Space.riv
    - assets/RiveAssets/Cosmos.riv
    - assets/RiveAssets/Orbit.riv
    - assets/RiveAssets/Love2.riv
    - assets/RiveAssets/Arrow.riv
    - assets/RiveAssets/Astronaut.riv
    - assets/RiveAssets/AI.riv
    - assets/RiveAssets/AI2.riv
  # Icon Social Media asset 
    - assets/icon/facebook.png
    - assets/icon/instagram.png
    - assets/icon/linkedin.png
    - assets/icon/whatsapp.png
    - assets/icon/mail.png
  # Foto
    - assets/foto/fotoProfile.jpg
    - assets/foto/apps development.png
    - assets/foto/Electro_proddev.png
    - assets/foto/mechatronic_forklift.png
  # Document
    - assets/textFile/PrivacyNPolicy.md
    - assets/textFile/TermsNCondition.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
